#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'

ENV['RAILS_ENV'] ||= 'production'

class WrappedCommnad < Delayed::Command
  def run(worker_name = nil)
    ActiveRecord::Base.connection.reconnect!
    Logger.new(File.join(Rails.root, 'log', 'delayed_job.log')).log(1, 'succeffully decorated')
    super(worker_name)
  end
end

WrappedCommnad.new(ARGV).daemonize